version: "3.8"

services:
  backend:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://webapp:password@db:5432/webapp
      - SECRET_KEY=your-secret-key
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webapp -d webapp"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
